import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Mail, FileText, ListTodo, Search, MessageSquare, Sparkles, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({
    meta: [
      { title: "WorkAI — AI Workplace Productivity Assistant" },
      { name: "description", content: "An integrated AI dashboard with email writing, meeting summaries, task planning, research and a chatbot." },
    ],
  }),
});

const features = [
  { title: "Smart Email Generator", desc: "Draft polished emails in any tone in seconds.", url: "/email", icon: Mail },
  { title: "Meeting Notes Summarizer", desc: "Turn long notes into summaries, decisions and action items.", url: "/summarizer", icon: FileText },
  { title: "AI Task Planner", desc: "Generate prioritized daily and weekly schedules.", url: "/planner", icon: ListTodo },
  { title: "AI Research Assistant", desc: "Summarize topics with insights and recommendations.", url: "/research", icon: Search },
  { title: "AI Chatbot", desc: "Conversational workplace assistant for any question.", url: "/chat", icon: MessageSquare },
];

function Index() {
  return (
    <div className="px-6 py-10 md:px-10 max-w-6xl mx-auto">
      <div
        className="rounded-2xl p-8 md:p-12 mb-10 text-primary-foreground shadow-lg"
        style={{ background: "var(--gradient-primary)", boxShadow: "var(--shadow-elegant)" }}
      >
        <div className="flex items-center gap-2 text-sm opacity-90">
          <Sparkles className="h-4 w-4" /> Powered by Lovable AI
        </div>
        <h1 className="text-3xl md:text-5xl font-bold mt-3 tracking-tight">
          Your AI workplace, all in one dashboard.
        </h1>
        <p className="mt-3 max-w-2xl text-base md:text-lg opacity-90">
          Write better emails, summarize meetings, plan your day, research topics and chat with an
          AI assistant — without leaving the app.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {features.map((f) => (
          <Link key={f.url} to={f.url}>
            <Card className="h-full transition-all hover:-translate-y-1 hover:shadow-lg border-border/60">
              <CardHeader>
                <div className="h-10 w-10 rounded-lg bg-accent flex items-center justify-center text-accent-foreground mb-2">
                  <f.icon className="h-5 w-5" />
                </div>
                <CardTitle className="text-lg">{f.title}</CardTitle>
                <CardDescription>{f.desc}</CardDescription>
              </CardHeader>
            </Card>
          </Link>
        ))}
      </div>

      <div className="mt-10 rounded-xl border bg-card p-5 flex gap-3 items-start">
        <ShieldCheck className="h-5 w-5 mt-0.5 text-primary shrink-0" />
        <div className="text-sm text-muted-foreground">
          <span className="font-medium text-foreground">Responsible AI notice.</span> Outputs are
          generated by AI and may be incomplete or inaccurate. Always review and edit before using
          them in real workplace communication. Avoid sharing confidential or personal data.
        </div>
      </div>
    </div>
  );
}
